### PR TITLE
Downloaded UI image from GHCR

### PR DESCRIPTION
**Pull request by dsimog01**
The UI is now downloaded from the GitHub Container Registry and the environment variables needed are set before it being served.

### CODE REVIEW

**Comment by dsimog01** [comment]
Release hash: /ipfs/Qmb5TeY8zr4JVYX9XYMQZfKohrkz1vH2VdN5k2BJciJhYo
Installer URL: http://my.dappnode/#/installer/%2Fipfs%2FQmb5TeY8zr4JVYX9XYMQZfKohrkz1vH2VdN5k2BJciJhYo
IPFS Peer: http://my.dappnode/#/system/add-ipfs-peer/%2Fdns4%2F5cd427552c3d47db.dyndns.dappnode.io%2Ftcp%2F4001%2Fipfs%2F12D3KooWDEkSd12b7AbC4rcHQc6XbfLhrzCTuN99bETt3McwCKPf

Testing steps: https://hackmd.io/lSGNPsIkQ6OAKxUF6pXyeA?view

**Review by pablomendezroyo — APPROVED** [review]

**Comment by pablomendezroyo** [comment]
Deppends on https://github.com/dappnode/eth2-keymanager-frontend/pull/47

**Review by pablomendezroyo — APPROVED** [review]

**Comment by dsimog01** [comment]
@tropicar

**Comment by tropicar** [comment]
> @tropicar

I am doing the last testing round and I will merge it. We include the latest version of web3signer.

**Pull request merged**
